NHSDigital/dtos-manage-breast-screening

manage_breast_screening/config/.env.tpl, manage_breast_screening/config/settings.py
Make the logging more verbose. This PR is stacked on top of https://github.com/NHSDigital/manage-breast-screening-django-spike/pull/3
While debugging deployment to Azure we didn't get any logging out of Django, so I wanted to check it's actually configured correctly. It is - but the formatting is inconsistent with Gunicorn, and we could do with DEBUG
logging as well at least in the short term.
We are expecting to run gunicorn with log level DEBUG also, so that it logs the requests being made.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other …
=> Add further log configuration

Makefile, manage_breast_screening/clinics/tests/test_models.py, manage_breast_screening/config/settings.py, manage_breast_screening/config/settings_test.py, manage_breast_screening/config/urls.py, manage_breast_screening/record_a_mammogram/admin.py, manage_breast_screening/record_a_mammogram/apps.py, manage_breast_screening/record_a_mammogram/forms.py, manage_breast_screening/record_a_mammogram/tests/test_forms.py, manage_breast_screening/record_a_mammogram/tests/test_views.py, manage_breast_screening/record_a_mammogram/urls.py, manage_breast_screening/record_a_mammogram/views.py, manage_breast_screening/templates/layout-app.html, manage_breast_screening/templates/record_a_mammogram/appointment_cannot_go_ahead.jinja, manage_breast_screening/templates/record_a_mammogram/ask_for_medical_information.jinja, manage_breast_screening/templates/record_a_mammogram/awaiting_images.jinja, manage_breast_screening/templates/record_a_mammogram/record_medical_information.jinja, manage_breast_screening/templates/record_a_mammogram/start_screening.jinja, manage_breast_screening/templates/wizard_step.jinja, pyproject.toml
This supercedes https://github.com/NHSDigital/manage-breast-screening/pull/18
We're thinking that each step in the form will persist progress to the database. There will likely be some duplication/boilerplate in the view layer, but we will address this later if it becomes difficult to work with.
The record a mammogram journey is a multi-step journey where steps can be skipped based on the information submitted. We want to set up a basic template so that we can start working on the individual pages and aligning them with the [prototype](https://github.com/NHSDigital/manage-breast-screening-prototype/tree/main/app/views/events/mammography).
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable …
=> Add minimal views for each step in the record a mammogram journey

manage_breast_screening/assets/sass/main.scss, manage_breast_screening/config/jinja2_env.py
Unbenownst to me, NHS Frontend already includes a no-wrap class.
---
=> Swap to using inbuilt NHS class rather than custom class

Dockerfile, package-lock.json, package.json
sass-embedded:
> This package is an alternative to the sass package. It supports the
same JS API as sass and is maintained by the same team, but where the sass package is pure JavaScript, sass-embedded is instead a JavaScript wrapper around a native Dart executable. This means sass-embedded will generally be much faster especially for large Sass compilations, but it can only be installed on the platforms that Dart supports: Windows, Mac OS, and Linux.
https://www.npmjs.com/package/sass-embedded
The docker build was using a newer version of node, 24, whereas our .tool-versions is 22. These should both be 22, which is the LTS release.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / …
=> Replace sass with sass-embedded, and fix docker build to node 22

manage_breast_screening/record_a_mammogram/views.py, manage_breast_screening/templates/record_a_mammogram/start_screening.jinja
This adds the secondary navigation component. It's currently non-functional as we haven't built the other pages.
When the appointment reaches a screened or partially screened state, the user will be able to navigate to any of these stages, so they can review the information.
Even though it's not functional yet, I'm adding it now so we have the basic layout in place.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We …
=> Appointment secondary navigation

.gitleaksignore
Caused by **https://github.com/NHSDigital/manage-breast-screening/pull/48**
These are publicly known IDs and can be ignored
The file numbers may have to be updated if the code moves. Once merged we should pin to the commit hash to avoid this issue.
=> Fix gitleaks false positives from resource_group_init

manage_breast_screening/clinics/models.py, manage_breast_screening/clinics/presenters.py, manage_breast_screening/clinics/tests/test_presenters.py, manage_breast_screening/clinics/views.py, manage_breast_screening/config/jinja2_env.py, manage_breast_screening/record_a_mammogram/presenters.py, manage_breast_screening/record_a_mammogram/tests/test_presenters.py, manage_breast_screening/record_a_mammogram/views.py, manage_breast_screening/templates/_components/appointment-header/macro.jinja, manage_breast_screening/templates/_components/appointment-header/template.jinja, manage_breast_screening/templates/_components/appointment-status/macro.jinja, manage_breast_screening/templates/_components/appointment-status/template.jinja, manage_breast_screening/templates/_components/participant-details/macro.jinja, manage_breast_screening/templates/_components/participant-details/template.jinja, manage_breast_screening/templates/_components/secondary-navigation/macro.jinja, manage_breast_screening/templates/clinics/index.html, manage_breast_screening/templates/record_a_mammogram/appointment_cannot_go_ahead.jinja, manage_breast_screening/templates/record_a_mammogram/ask_for_medical_information.jinja, manage_breast_screening/templates/record_a_mammogram/awaiting_images.jinja, manage_breast_screening/templates/record_a_mammogram/record_medical_information.jinja, manage_breast_screening/templates/record_a_mammogram/start_screening.jinja, manage_breast_screening/utils/string_formatting.py
This PR introduces [presenters](https://thoughtbot.com/blog/using-the-presenter-pattern-in-ruby-on-rails):
> The presenter pattern, sometimes called the “ViewModel” pattern, is essentially an intermediary between the model and the view. While the model handles core business logic and data, the presenter’s job is to prepare the model’s data specifically for display.
This was suggested by @colinrotherham in a previous PR and I thought it was a good idea to do now as the templates are getting quite complex.
So the goal of this PR is to:
- simplify the template logic
- remove the need for so many custom template filters
- test more of the code that formats data for display
As a proof of concept, I've migrated the start screening template to this approach in the second commit. If we're happy …
=> Extract a presenter (view model) layer

manage_breast_screening/record_a_mammogram/forms.py, manage_breast_screening/record_a_mammogram/tests/test_views.py, manage_breast_screening/record_a_mammogram/views.py, manage_breast_screening/templates/record_a_mammogram/ask_for_medical_information.jinja, manage_breast_screening/templates/wizard_step.jinja
This implements the second page in the record a mammogram journey.
https://github.com/NHSDigital/manage-breast-screening/pull/54 needs merging before this one
This adds the following copy (taken from the prototype)
Ask them about any:
- history of breast cancer
- lump examinations or biopsies
- other procedures in the breast or chest area
- recent breast changes or symptoms
- breast features (such as moles) that may appear on an x-ray
- relevant medication (such as HRT)
=> Ask for medical information page

manage_breast_screening/config/system_test_setup.py, manage_breast_screening/record_a_mammogram/tests/system/test_user_submits_cannot_go_ahead_form.py
This helper provides a convenient way to test form validations with
slightly more detail than simply asserting the presence of the error
on the page.
The helper:
- Asserts that the error link appears in the summary box
- Locates the error link by the expected id
- Locates the error within the expected fieldset
- Asserts that the error is a span with the expected id
I also attempted to write a test that checks the correct error is focused after clicking the link in the error summary, as outlined by Colin [here](https://github.com/NHSDigital/manage-breast-screening/pull/30#discussion_r2087051187).
This proved to be challenging, however. It is possible to retrieve the `document.activeElement` via playwright-python, using something like:
```python
summary_box.get_by_text(error_text).click() …
```
=> Add system test helper for validation errors

manage_breast_screening/record_a_mammogram/tests/system/test_user_submits_cannot_go_ahead_form.py, manage_breast_screening/record_a_mammogram/tests/test_forms.py
- Add a few more assertions to the system test for this page that check database state.
- Add a form test that checks the boolean value for reinvite is persisted correctly depending on the form data.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8998
Adding a load of database checks to system tests isn't really the done thing as they're supposed to be written as a set of user interactions with the system. I think a handful of basic checks are fine, but more thorough testing of database state (and validations for that matter) should probably be done in the view/form tests.
The form test I've added is an example of covering behaviour not adequately tested by the system test.
=> Additional tests for the cannot go ahead page

manage_breast_screening/config/system_test_setup.py, manage_breast_screening/record_a_mammogram/forms.py, manage_breast_screening/record_a_mammogram/tests/system/test_recording_a_mammogram.py, manage_breast_screening/record_a_mammogram/tests/system/test_user_submits_cannot_go_ahead_form.py, manage_breast_screening/templates/record_a_mammogram/appointment_cannot_go_ahead.jinja, manage_breast_screening/templates/wizard_step.jinja
We have a pattern for presenting errors at the top of the page. When you click on the error, the relevant field should be focused (rather than the previous behaviour of just navigating to the error)
In the case of checkboxes and radios, we need to link to the first option. Since the ErrorList object we are iterating over doesn't know whether the field contains checkboxes/radios, the easiest way to do this is to always link to [`ErrorList.field_id`](https://docs.djangoproject.com/en/5.2/ref/forms/api/#django.forms.ErrorList.field_id), which is the same Django-generated ID as [`field.auto_id`](https://docs.djangoproject.com/en/5.2/ref/forms/api/#django.forms.Form.auto_id), without a suffix like "-1", "-2" etc.
To make this all work, we have to explicitly set the `id` param of the first …
=> Correctly link errors to the matching form field

manage_breast_screening/templates/_components/secondary-navigation/macro.jinja, manage_breast_screening/templates/clinics/index.html, manage_breast_screening/templates/layout-app.html, manage_breast_screening/templates/record_a_mammogram/ask_for_medical_information.jinja, manage_breast_screening/templates/record_a_mammogram/record_medical_information.jinja, manage_breast_screening/templates/record_a_mammogram/start_screening.jinja, manage_breast_screening/templates/wizard_step.jinja
We've opted to follow the convention of using snake_case in our jinja templates for any macros and blocks we write ourselves. Python logic appearing in templates should also be in snake_case. This should, in practice, mean that the only camelCase in our templates comes from external libraries.
Update our templates to follow these conventions.
Taking a quick look through the rendered screens in local dev and making sure they load correctly and look right would be a useful test of this.
=> Use snake case consistently in templates

package-lock.json
Since we belong to DTOS (digital transformation of screening), I've added the prefix to our repo name.
This gets reflected in the package-lock.json.
=> Rename repo to include dtos- prefix

.github/dependabot.yaml
For NPM, use the same groups as nhsuk-frontend.
For pip, create the following groups:
- updates related to frontend assets and templates
- updates related to infrastructure concerns, i.e. updates that
don't typically require code changes, but may still affect
the running of the app in non-local environments
- updates related to testing and linting
- updates related to dev tools
We should also ignore nhsuk-frontend updates, because they are not actionable until nhsuk-frontend-jinja is updated.
=> Add dependabot groups so we get less PRs

.pre-commit-config.yaml, pyproject.toml
Ruff does not currently do this on format, but we can do it as part of the check if we pass --fix.
This change means that running the linter (or pre-commit hook) will automatically change files.
P.S. there are some more rulesets we could enable here, and I'm thinking it would be good to have a django specific one in particular, but I've left it out of this PR for now...
https://docs.astral.sh/ruff/rules/
=> Automatically order imports

infrastructure/terraform/main.tf, infrastructure/terraform/networking.tf
Fix error:
```
Error: creating Managed Environment (Subscription: "67aab2fa-fcc7-49da-9dc6-cb90f0fa0628"
│ Resource Group Name: "rg-manbrs-dev-uks"
│ Managed Environment Name: "manage-breast-screening-dev"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: ManagedEnvironmentInvalidNetworkConfiguration: The environment network configuration is invalid: The delegated subnet cannot be used by any other Azure resources.
│ 
│   with module.container-app-environment.azurerm_container_app_environment.main,
│   on ../modules/dtos-devops-templates/infrastructure/modules/container-app-environment/main.tf line 1, in resource "azurerm_container_app_environment" "main":
│    1: resource "azurerm_container_app_environment" "main" {
│ 
│ creating Managed Environment …
```
=> Fix subnets

manage_breast_screening/mammograms/presenters.py, manage_breast_screening/participants/fixtures/participants.json, manage_breast_screening/participants/jinja2/participants/show.jinja, manage_breast_screening/participants/models.py, manage_breast_screening/participants/presenters.py, manage_breast_screening/participants/tests/factories.py, manage_breast_screening/participants/tests/system/test_participant_record.py, manage_breast_screening/participants/tests/test_models.py, manage_breast_screening/participants/tests/test_presenters.py, manage_breast_screening/participants/views.py
Display upcoming and past appointments on the participant record, to match the prototype.
Note that the design changed since we created the Jira ticket. We decided to focus just on appointments, rather than screening episodes, until we have a better understanding of what information would be useful to show at the level of a screening episode. We are also not yet showing any mammogram events that do not relate to the national breast screening programme.
If a section is empty, it is not shown, and if neither section is populated then we show "No screening history found".
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9247
There is a column in the design for type, but this is always "Screening" at the moment. Do we want to drop this?
It would be good to have some feedback on the tests, …
=> [DTOSS-9247] Participant record appointments section

.pre-commit-config.yaml
django-diagrams doesn't seem to handle duplicate model names. An error is thrown from the githook. 
Exclude notifications models for now.
=> Exclude notifications models from ERD generation

.tool-versions
The `v` prefix in `nodejs v22.14.0` does not work on Linux, I have verified that other OSes call `asdf install` successfully without this prefix.
Does `asdf install` work for your OS?
=> Fix asdf nodejs version identifier

manage_breast_screening/notifications/tests/test_mesh_client.py
There's a dependency on having a MESH sandbox running in a container for this test to work properly.
- Move `tests.py` to avoid module name collision with `manage_breast_screening.notifications.tests`
- Skip test until we have container for MESH running as part of CI setup.
=> Move mesh client test and skip temporarily

manage_breast_screening/notifications/management/commands/create_appointments.py, manage_breast_screening/notifications/tests/management/commands/test_create_appointments.py
A few things came out of testing this command with sample data stored in Azurite.
Some of the fixes in this PR are the difference between mocking the dependencies and the real world usage of Azure SDK libraries.
Also improves argument passing and command output.
The command runs fine with the sample data and creates `Clinic` and `Appointment` records...
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9895
=> Amend create appointments admin command

manage_breast_screening/clinics/jinja2/clinics/show.jinja, manage_breast_screening/clinics/presenters.py, manage_breast_screening/clinics/views.py, manage_breast_screening/core/jinja2/layout-app.jinja, manage_breast_screening/core/jinja2/wizard_step.jinja, manage_breast_screening/core/tests/jinja2/conftest.py, manage_breast_screening/core/tests/jinja2/test_base_template.py, manage_breast_screening/core/tests/jinja2/test_django_form_helpers.py, manage_breast_screening/mammograms/jinja2/mammograms/show/appointment_details.jinja, manage_breast_screening/mammograms/jinja2/mammograms/start_screening.jinja, manage_breast_screening/mammograms/presenters.py, manage_breast_screening/mammograms/views.py, manage_breast_screening/participants/views.py
While working on my ticket I noticed we never set the titles to anything other than "NHS".
This PR adds in titles, following the general pattern of "{heading} - Manage breast screening - NHS"
Except sometimes the caption is used instead of the heading, to avoid PII in page titles.
If an error is on the page, prefix with "Error: ". This is done automatically in the base template, as long as the form object is named "form".
I've defined `page_title` - the part of the title that is unique to the page - in the view context. It could also go in the template itself, but currently we are defining other headings in the view so thought it made sense for these values to live together.
=> feat: add proper titles to each page

manage_breast_screening/conftest.py, manage_breast_screening/core/services/auditor.py, manage_breast_screening/mammograms/tests/views/test_appointment_flow.py, manage_breast_screening/mammograms/tests/views/test_special_appointments.py, manage_breast_screening/mammograms/views/appointment_flow.py, manage_breast_screening/mammograms/views/special_appointments.py
This is not ticketed up but relates to the pre-mammogram discussion epic: https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8899
There are forms in the participants app that are still missing auditing but I think we can sort those out in a separate ticket.
I think the general rule we should be following is that anywhere we have a POST request, we should expect at least audit record to be created. If this is the case, we could check this using static analysis.
=> Add missing auditing to views (mammograms)

manage_breast_screening/notifications/management/commands/send_message_batch.py, manage_breast_screening/notifications/tests/factories.py, manage_breast_screening/notifications/tests/management/commands/test_send_message_batch.py
The MESH Inbox will be updated from NBSS when certain actions have been performed on an Appointment - Booked, Cancelled or Updated. The appointment `status` field will be one of:
'B' = Booked
'C' = Cancelled
'A' = Attended
'D' = DNA
We (currently) only want to send invites to participants if the Appointment is Booked, as that is the scope of our private beta work.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10349?workflowName=DTOSS%3A+Task+Workflow+v2&stepId=2
=> DTOSS-10349: Only send Appointments to Notify with Booked status

manage_breast_screening/core/form_fields.py, manage_breast_screening/core/tests/test_form_fields.py
Following on from https://github.com/NHSDigital/dtos-manage-breast-screening/pull/230
This extends the form field subclasses to include integer fields.
This one is not actually used directly in any templates at the moment, but I wanted to include it for completeness.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10410
=> [DTOSS-10410] extract IntegerField subclass

.github/workflows/scan-repository.yaml, .github/workflows/stage-1-commit.yaml
On the PR-triggered workflow, only run commit scans on commits reachable from the current branch. Do not include unrelated branches.
In a separate, scheduled workflow, do a full scan. (I will set up slack notifications for this shortly).
This should prevent issues with PRs being blocked unnecessarily. E.g. right now we have a false-positive added and fixed in one branch, but all other PRs are failing their CI because they don't have the exception in their .gitleaksignore.
As far as I can tell, `actions/checkout` doesn't provide a nice way to say "fetch all the commits between the main branch (or merge base) and the current branch" - see https://github.com/actions/checkout/issues/520 for a discussion of the workarounds.
=> Limit secret scanning in CI to the commits on the branch

manage_breast_screening/notifications/management/commands/send_message_batch.py, manage_breast_screening/notifications/services/queue.py, manage_breast_screening/notifications/tests/factories.py, manage_breast_screening/notifications/tests/management/commands/test_send_message_batch.py, manage_breast_screening/notifications/tests/services/test_queue.py
~~CI is currently broken so having to stack PR's temporarily! This builds on this first PR https://github.com/NHSDigital/dtos-manage-breast-screening/pull/278~~
If a MessageBatch fails to send for a recoverable reason, as declared currently in `send_message_batch`, then we send it to a queue to retry failed batches.
In future some code will be able to process the queue and determine what next steps are for the batch - e.g. if one Message has a validation error then we remove that Message. Or if the error was recoverable (e.g. a server timeout) then we just go ahead and retry.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10575
=> DTOSS- 10575 - add recoverable failures to retry queue

.azuredevops/pipelines/delete-review-app.yml, .azuredevops/pipelines/deploy.yml, .github/workflows/cicd-1-pull-request-closed.yaml, .github/workflows/cicd-1-pull-request.yaml, .github/workflows/cicd-2-main-branch.yaml, .github/workflows/stage-4-deploy.yaml, .gitleaksignore, README.md, docs/infrastructure/create-environment.md, docs/infrastructure/deployment.md, docs/infrastructure/infra-faq.md, infrastructure/terraform/resource_group_init/core.bicep, infrastructure/terraform/resource_group_init/keyVault.bicep, infrastructure/terraform/resource_group_init/main.bicep, infrastructure/terraform/resource_group_init/managedIdentity.bicep, infrastructure/terraform/resource_group_init/storage.bicep, scripts/bash/db_migrate.sh, scripts/bash/resource_group_init.sh, scripts/bash/wait_ado_pipeline.sh
Allow deploy a review app for each pull request. It's an opt-in feature, triggered when the `deploy` label is added to the PR.
It triggers github actions and azure devops to create the review app.
The URL is displayed as a PR comment.
When the PR is merged or closed, the review app is deleted.
There are now detailed infrastructure docs in `docs/infrastructure`.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10199
Try closing and opening the PR to create/delete the app
Check pipelines in Github actions and Azure devops
Validate the new documentation
Check the dev environment
=> [DTOS-10199] Review apps pipeline

.github/workflows/cicd-1-pull-request.yaml, .github/workflows/cicd-2-main-branch.yaml, .vscode/settings.json, README.md, docs/adr/ADR-003-Subclass_Django_Form_fields.md, docs/infrastructure/create-environment.md, docs/infrastructure/deployment.md, docs/infrastructure/infra-faq.md, manage_breast_screening/notifications/compose.yml, manage_breast_screening/participants/tests/factories.py, scripts/shared.mk
If `.ONESHELL` is set in a Makefile, the `-e` option [must be passed to the shell](https://www.gnu.org/software/make/manual/html_node/One-Shell.html). However, there was a typo in `.SHELLFLAGS` that prevented it from being picked up.
`-e` in bash means "Exit immediately if a command exits with a non-zero status."
Adding to the confusion, version 3.81 of make applied the `-e` behaviour regardless of the typo, but 3.82 onwards didn't, leading to different results on different machines.
Since we have phony tasks with multiple test commands in, this was allowing build failures to pass undetected.
I've tested the fix with a stripped down example:
.PHONY: debug
debug:
false
echo "This should not print"
.ONESHELL:
.SHELL := /bin/bash
.SHELLFLAGS := -cex
This typo must have crept in when I …
=> fix SHELLFLAGS typo that prevents exiting on first failure

docs/infrastructure/create-environment.md, manage_breast_screening/notifications/queries/failures.py, manage_breast_screening/notifications/tests/factories.py, manage_breast_screening/notifications/tests/queries/test_failures.py
Adds a query class for the Private Beta failures report which returns a `django.db.QuerySet` instance. The queryset can be executed or turned into raw SQL as needed. 
This query can be used by the `pandas` library to generate CSV output via a `pandas.DataFrame` including any date/string transformations and formatting.
The query defaults to returning data from today, although a `datetime` can be passed in order to query data for a specific day. We could extend this to a weekly date range easily if necessary.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10660
=> Add failures report query

.azuredevops/pipelines/deploy.yml, .github/workflows/cicd-2-main-branch.yaml, .github/workflows/stage-4-deploy.yaml, infrastructure/environments/review/variables.tfvars, infrastructure/modules/container-apps/postgres.tf, infrastructure/modules/container-apps/variables.tf, infrastructure/terraform/main.tf, infrastructure/terraform/variables.tf, scripts/bash/wait_ado_pipeline.sh, scripts/terraform/terraform.mk
Varies changes in this PR: -
- Increase the github action workflow timeout for the ADO from 5 minutes to 1 hour
- Remove the azurerm_management_lock resource lock on the database as its better managed when its manually added to the database and outside of IAC.
- Allow github action workflow to be able to "Call deployment pipeline" when it does not have a PR_Number associated with it, this is to allow the merge to main to rebuild the dev environment.
=> Fix pipeline review dev

infrastructure/environments/dev/variables.tfvars, infrastructure/environments/review/variables.tfvars, infrastructure/modules/container-apps/main.tf, infrastructure/modules/container-apps/postgres.tf, infrastructure/modules/container-apps/variables.tf, infrastructure/terraform/main.tf, infrastructure/terraform/variables.tf
This PR introduces support for running the database as a Docker container instead of using an Azure-managed database.
**Database as container**
Adds configuration to run PostgreSQL as a container rather than relying solely on Azure Database for PostgreSQL.
**Seed demo data**
Parameterises seed_demo_data as a variable, allowing optional creation of demo seed data in the database.
**Random password management**
Generates a random password for the containerised PostgreSQL database.
Stores the password as a secret in:
- the WebApp Container App
- the Database Container App
- the Database Setup Container App job
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10700
In file **infrastructure/environments/\<environment\>/variables.tfvars** update variable **deploy_database_as_container** and …
=> [DTOSS-10700] use a docker image for the postgres database for the review apps testing

manage_breast_screening/notifications/management/commands/create_appointments.py, manage_breast_screening/notifications/management/commands/send_message_batch.py, manage_breast_screening/notifications/tests/queries/test_aggregate_query.py
Simplifies a few places where we called `datetime.today()` and then `datetime.replace(tzinfo=...)` to set the timezone.
Uses shorter `datetime.now(tz)` form.
=> Use `datetime.now(tz)` wherever possible

.github/workflows/stage-2-test.yaml
https://github.com/NHSDigital/dtos-manage-breast-screening/pull/375 attempted to make integration tests a separate downstream job from unit tests because of timeouts.
However the conditional [here](https://github.com/NHSDigital/dtos-manage-breast-screening/pull/375/files#diff-3510967c7b78ce8f5dc041f5252da1aab8dd63ef3b872a9f5fa78235d60de03cR102) which controls whether we run the integration tests did not work as expected and integration tests are being run for any changes, not just those particular to the notifications app.
This PR amends the `if` statement so that it uses the output from the `test` job properly.
See https://github.com/NHSDigital/dtos-manage-breast-screening/actions/runs/17582614042 for job being skipped.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10856
=> Fix conditional statement for integration test job

manage_breast_screening/config/.env.tpl, manage_breast_screening/notifications/services/api_client.py, manage_breast_screening/notifications/tests/dependencies/notify_api_stub/app.py, manage_breast_screening/notifications/tests/integration/test_api_client_can_call_notify_api.py, manage_breast_screening/notifications/tests/integration/test_retry_message_batches_from_queue.py, manage_breast_screening/notifications/tests/integration/test_send_message_batches_for_episode_types.py, manage_breast_screening/notifications/tests/services/test_api_client.py
This no longer needs to be sent in the headers of batch requests as it was used by [CMAPI](https://github.com/NHSDigital/dtos-communication-management)
We should now be calling NHS Notify direct.
[DTOSS-10944](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10944)
(NOTE: for integration tests to pass locally you need to re-build the notify-api-stub container)
=> DTOSS-10944: remove CMAPI consumer api key

manage_breast_screening/notifications/data/clinic_location_data.json
the `location_description` and `location_url` will be used in the personalisation fields when sending out appointment invites - this JSON data can be used to cross reference with Clinic data on our db to get the values. This is a quick solution for private beta as a way to reference this data without having to interfere with any existing data or data sources.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10753
=> DTOSS-10753: Add clinic location data

infrastructure/terraform/resource_group_init/core.bicep
This PR extends the managed identity's RBAC permissions to support Azure Storage operations by adding Storage Blob Data Contributor and Storage Queue Data Contributor roles.
Key Changes:
- Added Storage Blob Data Contributor and Storage Queue Data Contributor role definitions to the roleID variable
- Updated the RBAC Administrator role assignment condition to allow the managed identity to assign these storage roles to other Managed identities
- The managed identity can now delegate Key Vault Secrets User, Storage Blob Data Contributor, and Storage Queue Data Contributor roles while maintaining principle of least privilege
Technical Details:
- Uses Azure's conditional role assignment feature to constrain which roles can be assigned
- Maintains security by only allowing assignment of …
=> DTOSS-10982: add storage data contributor roles to managed identity RBAC

manage_breast_screening/notifications/management/commands/store_mesh_messages.py, manage_breast_screening/notifications/services/mesh_inbox.py, manage_breast_screening/notifications/tests/integration/helpers.py, manage_breast_screening/notifications/tests/integration/test_mesh_client.py, manage_breast_screening/notifications/tests/integration/test_store_mesh_messages.py, manage_breast_screening/notifications/tests/management/commands/test_store_mesh_messages.py, manage_breast_screening/notifications/tests/services/test_mesh_inbox.py
In deployed environments we need to connect to a real MESH inbox using SSL.
This is done by providing certificates for verification.
This PR:
- Adds a `MeshInbox` service which handles reading certificate content from the environment (originating from Azure Keyvault).
- Adds unit test coverage for `store_mesh_messages` command.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10919
=> Connect to MESH using SSL

manage_breast_screening/assets/sass/main.scss, manage_breast_screening/core/template_helpers.py, manage_breast_screening/core/utils/date_formatting.py, manage_breast_screening/core/utils/tests/test_date_formatting.py, manage_breast_screening/data/east_tester_today_clinic_data.yml, manage_breast_screening/mammograms/admin.py, manage_breast_screening/mammograms/jinja2/mammograms/record_medical_information.jinja, manage_breast_screening/mammograms/presenters/__init__.py, manage_breast_screening/mammograms/presenters/appointment_presenters.py, manage_breast_screening/mammograms/presenters/last_known_mammogram_presenter.py, manage_breast_screening/mammograms/presenters/medical_information_presenter.py, manage_breast_screening/mammograms/tests/presenters/test_appointment_presenters.py, manage_breast_screening/mammograms/tests/presenters/test_last_known_mammogram_presenter.py, manage_breast_screening/mammograms/tests/presenters/test_medical_information_presenter.py, manage_breast_screening/mammograms/tests/views/test_appointment_flow.py, manage_breast_screening/mammograms/views/appointment_flow.py, manage_breast_screening/nonprod/management/commands/seed_demo_data.py, manage_breast_screening/participants/tests/factories.py
In order to implement the forms for recording symptoms, we need to make sure they are shown to users on the record medical information page.
The seed command for non prod environments also needs updating to handle symptom data.
This PR implements the symptoms card to match the prototype. A couple of things are left out, e.g. I didn't add subtype yet as it's not needed for the symptom types I'm implementing at the moment. The links will be added in the PR that adds the forms, and we will have one add link for each symptom type.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10971
- I've had to implement new helpers for formatting dates without a day component. I noticed there was an edge case not handled correctly by the prototype where the user enters the current month. I've made it …
=> [DTOSS-10724] show symptoms

manage_breast_screening/mammograms/forms/symptom_forms.py, manage_breast_screening/mammograms/presenters/medical_information_presenter.py, manage_breast_screening/mammograms/tests/forms/test_symptom_forms.py, manage_breast_screening/mammograms/tests/presenters/test_medical_information_presenter.py, manage_breast_screening/mammograms/urls.py, manage_breast_screening/mammograms/views/symptom_views.py, manage_breast_screening/nhsuk_forms/utils.py, manage_breast_screening/tests/system/clinical/test_recording_symptoms.py
This extends the form for adding lumps to also function as an update form. All the existing validation is unchanged.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10724
A few things I want to get a second opinion on here
1. I feel like I'm reinventing functionality of Django's [model form](https://docs.djangoproject.com/en/5.2/topics/forms/modelforms/) here. The reason we've not used model forms so far (I think both me and @malcolmbaig have both tried this with previous forms) is because our forms are more complicated than the basic use case; they have fields which are conditional on other fields, and sometimes there is not a clean mapping between form fields and model fields, e.g. in this one we have 'exact date' which is a multi field, but it corresponds to two integer fields on the …
=> [DTOS-10724] extend add lump form to handle changes

manage_breast_screening/notifications/management/commands/helpers/message_batch_helpers.py, manage_breast_screening/notifications/services/queue.py, manage_breast_screening/notifications/tests/integration/test_retry_message_batches_from_queue.py, manage_breast_screening/notifications/tests/management/commands/helpers/test_message_batch_helpers.py
Removes unnecessary JSON serialisation when persisting error messages.
A couple of small refactors.
Discovered when testing against integration NHS Notify API. Prevents message batches which fail validation from being retried.
=> [Bug] Remove extra json serialisation

manage_breast_screening/notifications/services/api_client.py, manage_breast_screening/notifications/tests/dependencies/notify_api_stub/Dockerfile, manage_breast_screening/notifications/tests/dependencies/notify_api_stub/app.py, manage_breast_screening/notifications/tests/dependencies/notify_api_stub/schema.json, manage_breast_screening/notifications/tests/factories.py, manage_breast_screening/notifications/tests/services/test_api_client.py
The NHS Notify schema validation check in our integration tests was giving us false positives.
We were sending NHS Number as an integer to NHS Notify API which is invalid according to their schema but integration tests were passing.
This PR:
- Fixes the schema validation check on the integration test dependency (Notify API Stub)
- Fixes the factory default for `Appointment#nhs_number` so that it is 10 digits
- Ensures the recipient NHS number property in the POST body sent to NHS Notify is converted to a string.
=> Fix notification integration test schema validation

manage_breast_screening/assets/sass/main.scss, manage_breast_screening/mammograms/jinja2/mammograms/record_medical_information.jinja
The `p:has()` approach is a bit brittle as it will stop working if other elements come before the inset text.
This is is only used on the record medical info page at the moment, so we can use utility classes to tweak the margins there. We're already applying them to the inset text.
This was suggested by @colinrotherham in another review.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10724
TBC: if we can live with a margin of 24px (nhsuk-u-margin-bottom-4) following the paragraph, then we can remove the conditional class there that changes it to 16px (nhsuk-u-margin-bottom-3)
=> use utility classes instead of overriding component styles

manage_breast_screening/participants/forms.py
Adding this class to match the prototype (noticed while working on something unrelated). Visually, the legend is not needed as it's contextualised by the radio button that reveals it.
=> visually hide `exact_date` legend

manage_breast_screening/assets/sass/main.scss, manage_breast_screening/core/jinja2/layout-confirmation.jinja, manage_breast_screening/mammograms/jinja2/mammograms/medical_information/symptoms/confirm_delete_lump.jinja, manage_breast_screening/mammograms/jinja2/mammograms/medical_information/symptoms/simple_symptom.jinja, manage_breast_screening/mammograms/presenters/medical_information_presenter.py, manage_breast_screening/mammograms/tests/presenters/test_medical_information_presenter.py, manage_breast_screening/mammograms/tests/views/test_symptom_views.py, manage_breast_screening/mammograms/urls.py, manage_breast_screening/mammograms/views/appointment_views.py, manage_breast_screening/mammograms/views/symptom_views.py, manage_breast_screening/tests/system/clinical/test_recording_symptoms.py
This adds a delete link to the bottom of the change form for adding a lump. Once the forms are extended to other symptom types, this will be too.
We decided to implement the interstitial confirmation page now, rather than leave it for later. We definitely want to have a confirmation step, because it's a destructive action that is not easy to undo, but we are thinking about progressively enhancing this to a modal so the interaction feels smoother. ([Jira ticket](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11111))
We don't have an established pattern for this kind of confirmation page, but there is a GOV.UK one I've used as a starting point: https://govuk-frontend-review.herokuapp.com/full-page-examples/confirm-delete
This is not perfect and will need further tweaks, but I've reviewed it …
=> [DTOS-10724] delete functionality for lumps

manage_breast_screening/mammograms/presenters/medical_information_presenter.py, manage_breast_screening/mammograms/tests/presenters/test_medical_information_presenter.py
I noticed a couple of bugs in how I'm formatting symptoms in the summary list. The date was missing the "ago" and if area is set to "other" it was missing the details text.
This is not completely done yet - there will be more changes as part of implementing skin changes and nipple changes.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10726
=> [DTOS-10724] fix a few formatting issues in the symptom summary list

.tool-versions, Dockerfile
~* Update dockerfile to use Node 22.14 (instead of 24.*)~
* Update dockerfile to use Node 22.20 (instead of 24.*)
* Update .tool-versions to 22.20
This is the latest LTS version.
=> Use Node 22.20
