.tool-versions, Makefile, README.md, package-lock.json, scripts/shared.mk
Update the makefile so that `make config` does everything you need to start running the app.
- Create a .env file
- Install all the asdf-managed tools
- Set up the githooks
- Set up poetry
- Run all the django setup commands
---
=> Automate more of the project setup in `make config`

docs/adr/ADR-001-Use_Django_framework.md
We decided to use Django. This PR finalises the ADR and moves in information from the flask spike (https://github.com/NHSDigital/manage-breast-screening-flask-spike/pull/1)
---
=> Finalise Django ADR

.gitignore, Makefile, package-lock.json
Fix a few small things related to setting up the app in development.
See commits for detail.
---
=> Minor fixes for dev setup

.github/workflows/stage-3-build.yaml
We are using Github packages to publish our images publicly. We don't yet have continuous deployment, but we will pull from that registry as part of the terraform apply (https://github.com/NHSDigital/manage-breast-screening/pull/5).
This sets up Github actions to publish the image from the github actions workflow, as documented here:
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
I've tested this on the branch and it all works fine.
Authentication is via the special GITHUB_ACTIONS secret, as documented here:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
The registry used is …
=> Automatically publish images to the registry

.browserslistrc, Dockerfile, Makefile, README.md, babel.config.json, manage_breast_screening/assets/js/index.mjs, manage_breast_screening/templates/layout-app.html, package-lock.json, package.json, rollup.config.mjs, scripts/copy_nhsuk_frontend.sh
Create a javascript bundle we can add app-specific javascript to. I will look at adding jest for unit testing in a follow up PR.
I'm planning on adding some javascript for progressive enhancement of the check in button, and this will grow to include other things.
I want to make sure we're running this code through babel so we can safely use ES6 syntax while supporting older browsers. Rollup will also handle minification and tree shaking.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase …
=> Add rollup

Makefile, package-lock.json, scripts/shared.mk
- Rename _install_dependencies to _install_tools, to distinguish it from
the dependencies task that installs poetry/npm libraries
- Add an assets task to handle building of frontend assets
- Add dependencies and assets to the config task
A complete dev environment capable of running the service should be
available after a call to `make config`.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your …
=> Update Makefile to fix dev setup

Makefile, README.md, manage_breast_screening/config/system_test_setup.py, manage_breast_screening/record_a_mammogram/tests/system/test_user_submits_cannot_go_ahead_form.py
Some small improvements to our test setup. See commits for detail.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8998
Part of ongoing improvements to our testing workflow.
---
=> 8998 Testing improvements

.gitignore, .tool-versions, Makefile, README.md, infrastructure/.gitignore, infrastructure/environments/dev/variables.sh, infrastructure/environments/dev/variables.tfvars, infrastructure/terraform/.terraform.lock.hcl, infrastructure/terraform/main.tf, infrastructure/terraform/networking.tf, infrastructure/terraform/output.tf, infrastructure/terraform/providers.tf, infrastructure/terraform/resource_group_init/core.bicep, infrastructure/terraform/resource_group_init/dns.bicep, infrastructure/terraform/resource_group_init/main.bicep, infrastructure/terraform/resource_group_init/managedIdentity.bicep, infrastructure/terraform/resource_group_init/privateEndpoint.bicep, infrastructure/terraform/resource_group_init/storage.bicep, infrastructure/terraform/variables.tf, scripts/terraform/terraform.mk
Deploy app to Azure container apps. The deployment is done manually for now, using makefile and terraform for convenience.
Follow the steps in the README to test it.
First step to deploy the app to Azure.
---
=> [DTOSS-8589] Container app deployment

Makefile, README.md, infrastructure/environments/dev/variables.sh, scripts/terraform/terraform.mk
This was missing from the PR: https://github.com/NHSDigital/manage-breast-screening/pull/48
Includes changing "make dev" to "make local" to avoid conflict with the "dev" environment.
=> [DTOSS-8324] Latest fixes from container app PR

.azuredevops/pipelines/deploy.yml, infrastructure/terraform/resource_group_init/core.bicep
- Delete "int" environment as it is not ready yet
- Amend the managed identity role assignment as it was too restrictive to run in the pipeline
=> [DTOS-9339] Pipeline fixes

.azuredevops/pipelines/deploy.yml, README.md, infrastructure/environments/dev/variables.tfvars, infrastructure/terraform/.terraform.lock.hcl, infrastructure/terraform/data.tf, infrastructure/terraform/main.tf, infrastructure/terraform/networking.tf, infrastructure/terraform/postgres.tf, infrastructure/terraform/providers.tf, infrastructure/terraform/variables.tf, manage_breast_screening/config/postgresql/base.py, manage_breast_screening/config/settings.py, poetry.lock, pyproject.toml
Deploy postgres server and database via terraform
Database migrations run after the terraform apply
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9416
Check the pipeline and the dev environment
=> [DTOSS-9416] Terraform for postgres

.azuredevops/pipelines/deploy.yml, scripts/bash/db_migrate.sh, scripts/docker/docker.lib.sh, scripts/shared.mk
The job is started asynchronously so unless we watch it, we don't know if it was successful or not
Add a script to watch the job
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9416
Check successful pipeline: https://dev.azure.com/nhse-dtos/dtos-manage-breast-screening/_build/results?buildId=19289&view=logs&j=acd4a25b-5407-5816-f337-5ac671a25186&t=d9f8981c-2fd3-554c-4aca-5a5a0d673d24
=> [DTOSS-9416] Wait for db migrate to finish

README.md, infrastructure/terraform/.terraform.lock.hcl, infrastructure/terraform/front_door.tf, infrastructure/terraform/resource_group_init/main.bicep, infrastructure/terraform/variables.tf, scripts/terraform/terraform.mk
Create a public endpoint for the dev environment using Azure front door
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9604
Run terraform plan to see the diff
The domain was tested and demo'd manually earlier
=> [DTOSS-9604] Front door

manage_breast_screening/notifications/migrations/0007_channelstatus_messagestatus.py
This wasn't indexed correctly and pointed to the wrong dependency. 
Failure in `main` branch: https://github.com/NHSDigital/dtos-manage-breast-screening/actions/runs/16774574186/job/47497482169
=> Fix out of sync migration

manage_breast_screening/notifications/management/commands/store_mesh_messages.py, manage_breast_screening/notifications/tests/integration/test_store_mesh_messages.py
Acknowledge mesh message on after save to blob storage
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9916
=> [DTOSS-9916] Acknowledge mesh message on save to blob storage

README.md, docs/infrastructure/infra-faq.md, infrastructure/environments/review/variables.sh, infrastructure/environments/review/variables.tfvars, infrastructure/modules/container-apps/data.tf, infrastructure/modules/container-apps/front_door.tf, infrastructure/modules/container-apps/main.tf, infrastructure/modules/container-apps/output.tf, infrastructure/modules/container-apps/postgres.tf, infrastructure/modules/container-apps/providers.tf, infrastructure/modules/container-apps/variables.tf, infrastructure/modules/infra/main.tf, infrastructure/modules/infra/networking.tf, infrastructure/modules/infra/output.tf, infrastructure/modules/infra/providers.tf, infrastructure/modules/infra/variables.tf, infrastructure/terraform/.terraform.lock.hcl, infrastructure/terraform/data.tf, infrastructure/terraform/main.tf, infrastructure/terraform/output.tf, infrastructure/terraform/resource_group_init/dns.bicep, infrastructure/terraform/resource_group_init/main.bicep, scripts/bash/01-setup-groups.sh.template, scripts/bash/resource_group_init.sh, scripts/terraform/terraform.mk
Refactor terraform to allo building review apps without rebuilding the infrastructure.
Tasks:
```
Create a New Spoke VNet for Review Apps
Define a virtual network with the following address space: 10.140.0.0/16.
Create the following subnets:
snet-container-apps - 10.140.0.0/23 - delegated to `Microsoft.App/environments`
snet-main - 10.140.2.0/23
snet-postgres - 10.140.4.0/23
Peer the New Spoke with the Hub VNet
Create bidirectional VNet peering between the new spoke (10.140.0.0/16) and the existing hub.
Enable the following:
Forwarded traffic from the spoke to the hub.
Gateway transit from the hub (if required).
Reference: [VNet Peering](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview)
Deploy Azure Container Apps Environment
Use …
```
=> [DTOSS-10196] Review apps terraform

infrastructure/terraform/data.tf, infrastructure/terraform/resource_group_init/core.bicep
The refactoring for review apps caused dev to break. Fixing the data source condition.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10196
Run terraform-plan on dev
=> [DTOS-10196] Fix dev environment

manage_breast_screening/notifications/management/commands/create_appointments.py, manage_breast_screening/notifications/tests/fixtures/ABC_20241202091421_APPT_108.dat, manage_breast_screening/notifications/tests/integration/test_store_mesh_messages.py, manage_breast_screening/notifications/tests/management/commands/test_create_appointments.py
Linting error is affecting [all of CI and fixed here ](https://github.com/NHSDigital/dtos-manage-breast-screening/pull/317), not to do with code I've touched here.
In the MESH data we receive the field "Holding
Clinic" denotes a workflow step in NBSS.
If the dat file value for this field is "Y" we
should not save the appointment data.
We don't anticipate that Birmingham's data will
have this value as they don't use this workflow
but it is known to be used by other BSOs.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10643
=> DTOSS 10643: do not save "holding clinic" appointments

cis2_auth.md
Provide an outline of our CIS2 auth solution, including:
- Details of configuration variables needed by our CIS2 client
- An outline of the authentication flow
- Links to relevant CIS2 documentation
na
Does the doc provide enough detail? Does it provide a reasonably clear outline of what we've implemented?
=> Add doc for CIS2

docs/infrastructure/deployment.md, docs/infrastructure/infra-faq.md
- Front door FAQ
- Update review apps with container postgres
=> Infrastructure documentation

manage_breast_screening/notifications/management/commands/send_message_batch.py, manage_breast_screening/notifications/tests/management/commands/test_send_message_batch.py
We send a notification if the appointment date is in 4 weeks or less. Remove the additional 4 days.
See discussion: https://screening-discovery.slack.com/archives/C07538XCA1W/p1756978953232149
=> Amend appointment eligibility to 4 weeks

.github/workflows/stage-2-test.yaml, manage_breast_screening/notifications/README.md
Unit tests  + Integration tests were exceeding the 5 minute timeout.
This PR splits the two into separate jobs. If unit tests pass and there are changes detected in the notifications app codebase, we run the integration tests.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10856
=> Run notifications integration tests separately

manage_breast_screening/notifications/tests/integration/test_send_message_batches_for_episode_types.py
(and routing plans)
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10865
I've gone with iterating through all the routing plans rather than hard coding the values we would expect, as that is covered by unit tests - this should give us confidence that it's wired together correctly?
=> DTOSS-10865: Test message batches are sent for all episode types

manage_breast_screening/notifications/services/api_client.py, manage_breast_screening/notifications/tests/integration/test_api_client_can_call_notify_api.py, manage_breast_screening/notifications/tests/integration/test_retry_message_batches_from_queue.py, manage_breast_screening/notifications/tests/integration/test_send_message_batches_for_episode_types.py, manage_breast_screening/notifications/tests/services/test_api_client.py, manage_breast_screening/notifications/tests/test_views.py, manage_breast_screening/notifications/tests/validators/test_request_validator.py, manage_breast_screening/notifications/validators/request_validator.py
The environment variable for notifications didn't describe the services they were intended for use with. 
This PR updates them to denote whether they are for use with NHS Notify API or the API OAuth provider.
=> Amend notifications env var keys

.azuredevops/pipelines/deploy.yml, .github/workflows/cicd-2-main-branch.yaml, .github/workflows/stage-4-deploy.yaml, docs/infrastructure/create-environment.md, docs/infrastructure/infra-faq.md, infrastructure/environments/dev/variables.sh, infrastructure/environments/preprod/variables.sh, infrastructure/environments/preprod/variables.tfvars, infrastructure/environments/review/variables.sh, infrastructure/modules/container-apps/postgres.tf, infrastructure/terraform/resource_group_init/main.bicep, scripts/bash/db_run_job.sh, scripts/terraform/terraform.mk
As a DevOps engineer, I want to deploy the Pre-Production environment for the project [dtos-manage-breast-screening](https://github.com/NHSDigital/dtos-manage-breast-screening), so validate feature flags, and perform end-to-end checks before promoting to Production.
Subscription HUB: Hub subscription: Digital Screening DToS - Core Services Prod Hub - id 950605a3-9919-4da7-8942-e46e388a3851
Pre-production subscription: Digital Screening DToS - Core Services PreProd - id 649abc55-66a5-4e68-b97c-e59a18ba61d3
Follow the [create-environment.md](https://github.com/NHSDigital/dtos-manage-breast-screening/blob/main/docs/infrastructure/create-environment.md) to create the new environment 
Address space: 10.10.0.0/16
Building the pre prod environment for the MANBRS project. Take note that this will …
=> Dtoss 10958 add pre production environment

infrastructure/environments/review/variables.sh, infrastructure/environments/review/variables.tfvars, infrastructure/modules/container-apps/main.tf, infrastructure/modules/container-apps/postgres.tf
This alert was very hard to test: - 
Also put in default values for alarms as per JIRA https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11103
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11103
=> [DTOSS-11103] Test out the container restart alert

infrastructure/modules/container-apps/jobs.tf
Change cron expression from never running to running once an hour for the create appointments job
Has been tested on Azure, and the job runs on the hour
=> add cron expression every hour for job

manage_breast_screening/notifications/management/commands/create_appointments.py
Screenshot with unintuitive `None updated` logging message. This was captured testing on dev environment where the data file contained an update to an appointment which we did not have in the database.
Fixes for logging from `create_appointments` command
We need to log whether we are creating an appointment, updating an appointment ie. cancelling or marking as completed. 
Also adds a log entry for where an update would take place but the appointment is not found in the database.
=> Refactor create_appointments logging
